courses/Controllers/CoursesController.cs
using courses.Database;
using courses.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace courses.Controllers
{
    public class CoursesController : Controller
    {
        ApplicationDbContext _context;
        IWebHostEnvironment webHostEnvironment;

        public CoursesController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            this.webHostEnvironment = webHostEnvironment;
        }



        public IActionResult GetIndexView()
        {
            return View("Index", _context.courses.ToList());
        }
        public IActionResult GetCreateView()
        {
            return View("CreateCourse");
        }
        [HttpPost]
        public IActionResult AddCourse(Course curs, IFormFile? imageFormFile)
        {
           

            _context.courses.Add(curs);
            _context.SaveChanges();
            return RedirectToAction("GetIndexView");
        }

        [HttpGet]
        public IActionResult GetDetailsView(int id)
        {
            Course course = _context.courses.FirstOrDefault(x => x.Id == id);
            ViewBag.CourseDetails = course;

            if (course != null)
            {
                return View("Details", course);
            }
            else
                return NotFound();
        }


        [HttpGet]
        public IActionResult GetEditView(int id)
        {
            Course cors = _context.courses.FirstOrDefault(y => y.Id == id);
            if (cors != null)
            {
                return View("Edit", cors);
            }
            else
                return NotFound();
        }
        [HttpPost]
        public IActionResult Edit(Course curs, IFormFile? imageFormFile)
        {

            _context.courses.Update(curs);
            _context.SaveChanges();

            return RedirectToAction("GetIndexView");
        }
 
        [HttpGet]
        public IActionResult GetDeleteView(int id)
        {
            Course course = _context.courses.Include(d => d.Teacher).FirstOrDefault(d => d.Id == id);
            if (course != null)
            {
                return View("Delete", course);
            }
            else
                return NotFound();
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            Course course = _context.courses.Find(id);

            _context.courses.Remove(course);
            _context.SaveChanges();

            return RedirectToAction("GetIndexView");
        }
    }

}

courses/Controllers/StudentsController.cs
using courses.Database;
using courses.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace courses.Controllers
{
    public class StudentsController : Controller
    {
        ApplicationDbContext _context;
        IWebHostEnvironment webHostEnvironment;

        public StudentsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            this.webHostEnvironment = webHostEnvironment;
        }
        public IActionResult GetIndexView()
        {
            return View("Index", _context.Students.ToList());
        }
        public IActionResult GetCreateView() 
        {
            return View("CreateStudent");
        }
        [HttpPost]
        public IActionResult AddStudent(Student stud, IFormFile? imageFormFile)
        {
            if (imageFormFile != null)
            {
                string imgExtention = Path.GetExtension(imageFormFile.FileName);
                Guid imgGuid = Guid.NewGuid();
                string imageName = imgGuid + imgExtention;
                string imagePath = "\\Image\\" + imageName;
                stud.ImagePath = imagePath;
                string imgFullPath = webHostEnvironment.WebRootPath + imagePath;
                FileStream imgFileStream = new FileStream(imgFullPath, FileMode.Create);
                imageFormFile.CopyTo(imgFileStream);
                imgFileStream.Dispose();
            }
            else
            {
                stud.ImagePath = "\\Image\\No_Image.png";
            }
            _context.Students.Add(stud);
            _context.SaveChanges();
            return RedirectToAction("GetIndexView");
        }

        [HttpGet]
        public IActionResult GetDetailsView(int id) 
        {
            Student student = _context.Students.FirstOrDefault(x => x.Id == id);
            ViewBag.StudentDetails = student;

            if (student != null)
            {
                return View("Details", student);
            }
            else
                return NotFound();
        }
        [HttpGet]
        public IActionResult GetEditView(int id) 
        {
            Student student= _context.Students.FirstOrDefault(y => y.Id == id);
            if (student != null)
            {
                return View("Edit", student);
            }
            else
                return NotFound();
        }
        [HttpPost]
        public IActionResult Edit(Student stud, IFormFile? imageFormFile)
        {
            if (stud.ImagePath != "\\Image\\No_Image.png")
            {
                string oldImagePath = webHostEnvironment.WebRootPath + stud.ImagePath;
                System.IO.File.Delete(oldImagePath);

            }
          
                string imgExtention = Path.GetExtension(imageFormFile.FileName);
                Guid imgGuid = Guid.NewGuid();
                string imageName = imgGuid + imgExtention;
                string imagePath = "\\Image\\" + imageName;
                stud.ImagePath = imagePath;
                string imgFullPath = webHostEnvironment.WebRootPath + imagePath;
                FileStream imgFileStream = new FileStream(imgFullPath, FileMode.Create);
                imageFormFile.CopyTo(imgFileStream);
                imgFileStream.Dispose();
        
            _context.Students.  Update(stud);
            _context.SaveChanges();

            return RedirectToAction("GetIndexView");   
        }
        [HttpGet]
        public IActionResult GetDeleteView(int id) 
        {
            Student student=_context.Students.FirstOrDefault(d=>d.Id == id);
            if(student != null)
            {
                return View("Delete",student);
            }
            else
                    return NotFound();
        }
        [HttpPost]
        public IActionResult Delete(int id) 
        {
            Student student = _context.Students.Find(id);

            if (student != null && student.ImagePath != "\\images\\No_Image.png")
            {
                string imgFullPath = webHostEnvironment.WebRootPath + student.ImagePath;
                System.IO.File.Delete(imgFullPath);
            }

            return RedirectToAction("GetIndexView");
        }
    }

}

courses/Controllers/TeachersController.cs
using courses.Database;
using courses.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace courses.Controllers
{
    public class TeachersController : Controller
    {
        ApplicationDbContext _context;
        IWebHostEnvironment webHostEnvironment;

        public TeachersController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            this.webHostEnvironment = webHostEnvironment;
        }
        public IActionResult GetIndexView()
        {
            return View("Index", _context.teachers.ToList());
        }
        public IActionResult GetCreateView()
        {
            return View("CreateTeacher");
        }
        [HttpPost]
        public IActionResult AddTeacher(Teacher stud)
        {
           
            _context.teachers.Add(stud);
            _context.SaveChanges();
            return RedirectToAction("GetIndexView");
        }

        [HttpGet]
        public IActionResult GetDetailsView(int id)
        {
            Teacher Teacher = _context.teachers.FirstOrDefault(x => x.Id == id);
            ViewBag.TeacherDetails = Teacher;

            if (Teacher != null)
            {
                return View("Details", Teacher);
            }
            else
                return NotFound();
        }
        [HttpGet]
        public IActionResult GetEditView(int id)
        {
            Teacher Teacher = _context.teachers.FirstOrDefault(y => y.Id == id);
            if (Teacher != null)
            {
                return View("Edit", Teacher);
            }
            else
                return NotFound();
        }
        [HttpPost]
        public IActionResult Edit(Teacher stud)
        {
           

            _context.teachers.Update(stud);
            _context.SaveChanges();

            return RedirectToAction("GetIndexView");
        }
        [HttpGet]
        public IActionResult GetDeleteView(int id)
        {
            Teacher teacher = _context.teachers.Include(d => d.Course).FirstOrDefault(d => d.Id == id);
            if (teacher != null)
            {
                return View("Delete", teacher);
            }
            else
                return NotFound();
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            Teacher teacher = _context.teachers.Find(id);

            _context.Remove(teacher);
            _context.SaveChanges();

            return RedirectToAction("GetIndexView");
        }
    }

}

courses/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - courses</title>
   @* <link rel="stylesheet" href="~/css/bootstrap.min (2).css"  />*@
@*    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
*@    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/courses.styles.css" asp-append-version="true" />
	<link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
	<link href="~/css/bootstrap.min (1).css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">courses</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="GetIndexView">Students</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="GetIndexView">Courses</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachers" asp-action="GetIndexView">Teachers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - courses - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>